### ISSUE TITLE
problem with precss

### ISSUE THREAD

**Issue by mushiuta** [OEvgeny/postcss-atroot#2]
there has a problem with precss,when i use '@at-root' like you has said it doesn't work
this is the postcss file:
```postcss
.test{
  color:red;
  @at-root{
    .test2{
      color:blue;
    }
  }
}
```
and then the output file:
```css
.test{
  color:red;
  @at-root{
    .test2{
      color:blue;
    }
  }
}
```

**Comment by OEvgeny** [comment]
I did some tests. Looks like problem is in precss. Because:
```js
var postcss = require('postcss')
var precss = require('precss')
var scss = require('postcss-scss')

var css = postcss([precss()]).process(`
.test{
  color:red;
  @at-root{
    .test2{
      color:blue;
    }
  }
}
`, {parser: scss}).then(result => {
  console.log('precss', result.css)
})
```
Produces:
```css
precss 
.test{
  color:red;
  @at-root{
    .test2{
      color:blue;
    }
  }
}

```

But
```js
var atRoot = require('postcss-atroot')

css = postcss([atRoot()]).process(`
.test{
  color:red;
  @at-root{
    .test2{
      color:blue;
    }
  }
}
`).then(result => {
  console.log('atroot only', result.css)
})
```

Works well:
```css
atroot only .test2{
  color:blue
}
.test{
  color:red
}
```
